name: allrize-tech
region: nyc
domains:
  - domain: allrize.tech
    type: PRIMARY
    zone: allrize.tech
  - domain: www.allrize.tech
    type: ALIAS
    zone: allrize.tech
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
static_sites:
  - name: web
    git:
      repo_clone_url: https://github.com/rzrizaldy/rzrizaldy.github.io.git
      branch: master
    source_dir: /
    output_dir: /
    index_document: index.html
    error_document: index.html
    routes:
      - path: /
features:
  - buildpack-stack=ubuntu-22
